(() => {
'use strict';
const KEY='bidSheetV2';
const defaults={settings:{companyName:'',companyPhone:'',companyEmail:'',companyAddress:'',regularRate:0,otRate:0,dtRate:0,hoursPerWeek:40,taxRate:0,profit:20,overhead:0,taxLabor:false},customers:[],parts:[],estimates:[]};
let db=load(), current=null;
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0), num=id=>Number($(id).value)||0;
function load(){try{return Object.assign(structuredClone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{return structuredClone(defaults)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(db));}
function uid(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='saved')renderSaved();if(id==='customers')renderCustomers();if(id==='parts')renderParts();window.scrollTo(0,0)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function blankEstimate(){const s=db.settings;return{id:null,created:new Date().toISOString(),updated:new Date().toISOString(),jobName:'',customerId:'',address:'',contact:'',phone:'',elevators:'',groups:'',notes:'',regularHours:0,regularRate:s.regularRate,otHours:0,otRate:s.otRate,dtHours:0,dtRate:s.dtRate,weeks:0,hoursPerWeek:s.hoursPerWeek,parts:[],overhead:s.overhead,profit:s.profit,discount:0}}
function newEstimate(){current=blankEstimate();fillEstimate();showView('estimate');toast('New estimate ready')}
function fillEstimate(){const e=current||blankEstimate();$('estimateTitle').textContent=e.id?(e.jobName||'Saved Estimate'):'New Estimate';$('saveStatus').textContent=e.id?'Last saved '+new Date(e.updated).toLocaleString():'Not saved';
[['jobName','jobName'],['jobAddress','address'],['jobContact','contact'],['jobPhone','phone'],['elevators','elevators'],['groups','groups'],['notes','notes'],['regularHours','regularHours'],['regularRate','regularRate'],['otHours','otHours'],['otRate','otRate'],['dtHours','dtHours'],['dtRate','dtRate'],['weeks','weeks'],['hoursPerWeek','hoursPerWeek'],['overheadPct','overhead'],['profitPct','profit'],['discount','discount']].forEach(([id,k])=>$(id).value=e[k]??'');renderCustomerOptions(e.customerId);$('estimateParts').innerHTML='';(e.parts||[]).forEach(addEstimatePart);calc()}
function renderCustomerOptions(selected=''){$('customerSelect').innerHTML='<option value="">Select customer</option>'+db.customers.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('')}
$('customerSelect').onchange=()=>{const c=db.customers.find(x=>x.id===$('customerSelect').value);if(c){$('jobAddress').value=c.address||'';$('jobContact').value=c.contact||c.name||'';$('jobPhone').value=c.phone||c.email||''}calc()};
function addEstimatePart(p={name:'',qty:1,cost:0,tax:true}){const tr=document.createElement('tr');tr.innerHTML=`<td><input class="pname" list="partNames" value="${esc(p.name)}"><datalist id="partNames">${db.parts.map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist></td><td><input class="pqty" type="number" min="0" step=".01" value="${p.qty??1}"></td><td><input class="pcost" type="number" min="0" step=".01" value="${p.cost??0}"></td><td><input class="ptax" type="checkbox" ${p.tax!==false?'checked':''}></td><td class="ptotal">$0.00</td><td><button class="iconbtn" aria-label="Remove">×</button></td>`;tr.querySelector('.pname').addEventListener('change',ev=>{const lib=db.parts.find(x=>x.name.toLowerCase()===ev.target.value.toLowerCase());if(lib)tr.querySelector('.pcost').value=lib.cost;calc()});tr.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc));tr.querySelector('.iconbtn').onclick=()=>{tr.remove();calc()};$('estimateParts').appendChild(tr);calc()}
function calculations(){let labor=num('regularHours')*num('regularRate')+num('otHours')*num('otRate')+num('dtHours')*num('dtRate'),base=0,taxable=0;document.querySelectorAll('#estimateParts tr').forEach(r=>{const line=(Number(r.querySelector('.pqty').value)||0)*(Number(r.querySelector('.pcost').value)||0);r.querySelector('.ptotal').textContent=money(line);base+=line;if(r.querySelector('.ptax').checked)taxable+=line});if(db.settings.taxLabor)taxable+=labor;const tax=taxable*(Number(db.settings.taxRate)||0)/100,subtotal=labor+base+tax,overhead=subtotal*num('overheadPct')/100,profit=(subtotal+overhead)*num('profitPct')/100,discount=num('discount'),total=Math.max(0,subtotal+overhead+profit-discount);return{labor,base,tax,overhead,profit,discount,total}}
function calc(){const c=calculations();$('regularTotal').textContent=money(num('regularHours')*num('regularRate'));$('otTotal').textContent=money(num('otHours')*num('otRate'));$('dtTotal').textContent=money(num('dtHours')*num('dtRate'));$('laborSummary').textContent=money(c.labor);$('partsBaseSummary').textContent=money(c.base);$('taxSummary').textContent=money(c.tax);$('overheadSummary').textContent=money(c.overhead);$('profitSummary').textContent=money(c.profit);$('discountSummary').textContent='-'+money(c.discount);$('grandTotal').textContent=money(c.total)}
document.querySelectorAll('#estimate input,#estimate textarea').forEach(i=>i.addEventListener('input',calc));$('addPartBtn').onclick=()=>addEstimatePart();$('applyWeeks').onclick=()=>{$('regularHours').value=num('weeks')*num('hoursPerWeek');calc()};
function collect(){const e=current||blankEstimate();Object.assign(e,{jobName:$('jobName').value.trim(),customerId:$('customerSelect').value,address:$('jobAddress').value.trim(),contact:$('jobContact').value.trim(),phone:$('jobPhone').value.trim(),elevators:$('elevators').value,groups:$('groups').value,notes:$('notes').value.trim(),regularHours:num('regularHours'),regularRate:num('regularRate'),otHours:num('otHours'),otRate:num('otRate'),dtHours:num('dtHours'),dtRate:num('dtRate'),weeks:num('weeks'),hoursPerWeek:num('hoursPerWeek'),overhead:num('overheadPct'),profit:num('profitPct'),discount:num('discount'),parts:[...document.querySelectorAll('#estimateParts tr')].map(r=>({name:r.querySelector('.pname').value.trim(),qty:Number(r.querySelector('.pqty').value)||0,cost:Number(r.querySelector('.pcost').value)||0,tax:r.querySelector('.ptax').checked})),updated:new Date().toISOString(),totals:calculations()});return e}
function saveEstimate(){const e=collect();if(!e.jobName){toast('Enter a job name first');$('jobName').focus();return}if(!e.id){e.id=uid();db.estimates.unshift(e)}else{const i=db.estimates.findIndex(x=>x.id===e.id);if(i>=0)db.estimates[i]=e;else db.estimates.unshift(e)}current=e;persist();fillEstimate();toast('Estimate saved')}
function renderSaved(){const box=$('savedList');if(!db.estimates.length){box.innerHTML='<div class="empty">No estimates saved yet.</div>';return}box.innerHTML=db.estimates.map(e=>`<article class="listitem"><button class="itemmain" data-open="${e.id}"><b>${esc(e.jobName||'Untitled')}</b><span>${esc(db.customers.find(c=>c.id===e.customerId)?.name||e.contact||'No customer')} · ${new Date(e.updated).toLocaleDateString()}</span></button><strong>${money(e.totals?.total)}</strong><button class="more" data-copy="${e.id}">Copy</button><button class="delete" data-del="${e.id}">Delete</button></article>`).join('');box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=structuredClone(db.estimates.find(e=>e.id===b.dataset.open));fillEstimate();showView('estimate')});box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{const e=structuredClone(db.estimates.find(x=>x.id===b.dataset.copy));e.id=null;e.jobName+=' Copy';current=e;fillEstimate();showView('estimate')});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this estimate?')){db.estimates=db.estimates.filter(e=>e.id!==b.dataset.del);persist();renderSaved()}})}
function openEditor(type,obj={}){const isCustomer=type==='customer';$('dialogTitle').textContent=(obj.id?'Edit ':'Add ')+(isCustomer?'Customer':'Part');$('dialogFields').innerHTML=isCustomer?`<label>Name<input name="name" required value="${esc(obj.name)}"></label><label>Contact<input name="contact" value="${esc(obj.contact)}"></label><label>Phone<input name="phone" value="${esc(obj.phone)}"></label><label>Email<input name="email" value="${esc(obj.email)}"></label><label>Address<textarea name="address" rows="3">${esc(obj.address)}</textarea></label>`:`<label>Part name<input name="name" required value="${esc(obj.name)}"></label><label>Unit cost<input name="cost" type="number" step=".01" min="0" value="${obj.cost??0}"></label>`;$('editorForm').dataset.type=type;$('editorForm').dataset.id=obj.id||'';$('editorDialog').showModal()}
$('editorForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),type=e.target.dataset.type,id=e.target.dataset.id||uid(),list=type==='customer'?db.customers:db.parts,item=type==='customer'?{id,name:f.get('name').trim(),contact:f.get('contact').trim(),phone:f.get('phone').trim(),email:f.get('email').trim(),address:f.get('address').trim()}:{id,name:f.get('name').trim(),cost:Number(f.get('cost'))||0};if(!item.name)return;const i=list.findIndex(x=>x.id===id);i>=0?list[i]=item:list.push(item);persist();$('editorDialog').close();type==='customer'?renderCustomers():renderParts();renderCustomerOptions(current?.customerId);toast('Saved')};
function renderCustomers(){$('customerList').innerHTML=db.customers.length?db.customers.map(c=>`<article class="listitem"><button class="itemmain" data-edit="${c.id}"><b>${esc(c.name)}</b><span>${esc(c.contact||c.phone||c.email||c.address||'No details')}</span></button><button class="delete" data-del="${c.id}">Delete</button></article>`).join(''):'<div class="empty">No customers yet.</div>';bindLibrary('customer')}
function renderParts(){$('partsList').innerHTML=db.parts.length?db.parts.map(p=>`<article class="listitem"><button class="itemmain" data-edit="${p.id}"><b>${esc(p.name)}</b><span>${money(p.cost)} each</span></button><button class="delete" data-del="${p.id}">Delete</button></article>`).join(''):'<div class="empty">No saved parts yet.</div>';bindLibrary('part')}
function bindLibrary(type){const list=type==='customer'?db.customers:db.parts,box=$(type==='customer'?'customerList':'partsList');box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(type,list.find(x=>x.id===b.dataset.edit)));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Delete this item?')){const key=type==='customer'?'customers':'parts';db[key]=db[key].filter(x=>x.id!==b.dataset.del);persist();type==='customer'?renderCustomers():renderParts()}})}
function loadSettingsForm(){const s=db.settings;[['companyName','companyName'],['companyPhone','companyPhone'],['companyEmail','companyEmail'],['companyAddress','companyAddress'],['settingRegularRate','regularRate'],['settingOtRate','otRate'],['settingDtRate','dtRate'],['settingHoursWeek','hoursPerWeek'],['settingTaxRate','taxRate'],['settingProfit','profit'],['settingOverhead','overhead']].forEach(([id,k])=>$(id).value=s[k]??'');$('settingTaxLabor').checked=!!s.taxLabor}
function saveSettings(){db.settings={companyName:$('companyName').value.trim(),companyPhone:$('companyPhone').value.trim(),companyEmail:$('companyEmail').value.trim(),companyAddress:$('companyAddress').value.trim(),regularRate:num('settingRegularRate'),otRate:num('settingOtRate'),dtRate:num('settingDtRate'),hoursPerWeek:num('settingHoursWeek'),taxRate:num('settingTaxRate'),profit:num('settingProfit'),overhead:num('settingOverhead'),taxLabor:$('settingTaxLabor').checked};persist();calc();toast('Settings saved')}
$('saveBtn').onclick=saveEstimate;$('newEstimateBtn').onclick=newEstimate;$('printBtn').onclick=()=>window.print();$('addCustomerBtn').onclick=()=>openEditor('customer');$('addLibraryPartBtn').onclick=()=>openEditor('part');$('saveSettingsBtn').onclick=saveSettings;
$('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='bid-sheet-backup.json';a.click();URL.revokeObjectURL(a.href)};$('importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());db=Object.assign(structuredClone(defaults),data);persist();loadSettingsForm();newEstimate();toast('Backup imported')}catch{alert('That backup file could not be read.')}};$('clearAllBtn').onclick=()=>{if(confirm('Erase every estimate, customer, part, and setting?')){localStorage.removeItem(KEY);db=structuredClone(defaults);loadSettingsForm();newEstimate();toast('All data erased')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});loadSettingsForm();newEstimate();
})();